### ISSUE TITLE
Example sketch RS485SerialPassthroughTest does not compile

### ISSUE THREAD

**Issue by Erik84750** [sauttefk/RS485HwSerial#3]
Compile error on AVR (UNO, Pro Mini, ..): " 'RS485HwSerial1' was not declared in scope"
Compile error for ESP8266: exit status 1; Error when compiling.

**Comment by sauttefk** [comment]
The example only works on ATmegas that have 2 or more UARTs. Still you can use this library for the single UART these ATmegas have, but obviously there will be no forwarding between two hardware UARTs.

This library also works only for ATmegas and not for any other microcontrollers like ESP8266 or ESP32 as they have completely different IO-modules and the Ardiuno abstraction layer lies above the HAL created by the ESP-IDF.

**Comment by sauttefk** [comment]
@Erik84750 you also might want to take a look at the [MAX13487](https://datasheets.maximintegrated.com/en/ds/MAX13487E-MAX13488E.pdf) which automatically handles the transmit direction on a half duplex RS485 bus.
